// AUTO-GENERATED by export_2nd_to_js.py — do not edit manually.

export const PREPROCESSING_2ND = {
  "numericCols": [
    "GPA",
    "Prior_Internships",
    "Extra_Curricular_Activities",
    "Networking_Events_Attended",
    "Months_Searching",
    "Applications_Submitted",
    "First_Round_Interviews"
  ],
  "scalerMean": [
    3.196982625,
    1.1995125,
    2.0031375,
    3.0014875,
    6.496725,
    53.7381125,
    2.1685875
  ],
  "scalerScale": [
    0.3926093372528338,
    1.1231461446952262,
    1.4115072284950403,
    1.739873641200346,
    3.444116617418028,
    44.99724605392361,
    1.9114106714266692
  ],
  "oheCols": [
    "University_Rating_Mid-tier",
    "University_Rating_Top-tier",
    "School_Size_Medium",
    "School_Size_Small",
    "Region_Northeast",
    "Region_South",
    "Region_West",
    "Major_Category_Business",
    "Major_Category_Healthcare",
    "Major_Category_Humanities",
    "Major_Category_STEM",
    "Primary_Search_Platform_Indeed",
    "Primary_Search_Platform_LinkedIn"
  ],
  "featureNames": [
    "GPA",
    "Prior_Internships",
    "Extra_Curricular_Activities",
    "Networking_Events_Attended",
    "Months_Searching",
    "Applications_Submitted",
    "First_Round_Interviews",
    "University_Rating_Mid-tier",
    "University_Rating_Top-tier",
    "School_Size_Medium",
    "School_Size_Small",
    "Region_Northeast",
    "Region_South",
    "Region_West",
    "Major_Category_Business",
    "Major_Category_Healthcare",
    "Major_Category_Humanities",
    "Major_Category_STEM",
    "Primary_Search_Platform_Indeed",
    "Primary_Search_Platform_LinkedIn"
  ],
  "catCols": [
    "University_Rating",
    "School_Size",
    "Region",
    "Major_Category",
    "Primary_Search_Platform"
  ],
  "catValues": {
    "University_Rating": [
      "Lower-tier",
      "Mid-tier",
      "Top-tier"
    ],
    "School_Size": [
      "Large",
      "Medium",
      "Small"
    ],
    "Region": [
      "Midwest",
      "Northeast",
      "South",
      "West"
    ],
    "Major_Category": [
      "Arts",
      "Business",
      "Healthcare",
      "Humanities",
      "STEM"
    ],
    "Primary_Search_Platform": [
      "Handshake",
      "Indeed",
      "LinkedIn"
    ]
  },
  "catFirstDropped": {
    "University_Rating": "Lower-tier",
    "School_Size": "Large",
    "Region": "Midwest",
    "Major_Category": "Arts",
    "Primary_Search_Platform": "Handshake"
  },
  "nFeatures": 20
};
