"""
export_to_js.py
===============
One-time script: exports the Gradient Boosting model (ONNX) and preprocessing
parameters to files consumed by the static React frontend.

Run with:
    .venv/bin/python finalscript/export_to_js.py

Outputs:
    predictweb/public/model_offer.onnx   — ONNX model (loaded by onnxruntime-web)
    predictweb/src/lib/preprocessing_offer.js  — scaler params + OHE + form metadata
"""

import json
import pathlib

import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

# ── Paths ─────────────────────────────────────────────────────────────────────
WORKSPACE    = pathlib.Path(__file__).parent.parent
DATA_PATH    = WORKSPACE / "data" / "job_search_platform_efficacy_100k.csv"
MODEL_PATH   = WORKSPACE / "models" / "baseModelOffer" / "Gradient_Boosting_tuned.joblib"
OUT_LIB      = WORKSPACE / "predictweb" / "src" / "lib"
OUT_PUBLIC   = WORKSPACE / "predictweb" / "public"

# ── Mirrors CONFIG in train_and_export.py ─────────────────────────────────────
DROP_COLS = [
    "", "Student_ID", "Time_to_Offer_Days", "Offer_Salary",
    "Company_Size_Offered", "Role_Relevance", "Accepted_Offer",
]
TARGET_COL     = "Offer_Received"
NUMERIC_COLS   = [
    "GPA", "Prior_Internships", "Extra_Curricular_Activities",
    "Networking_Events_Attended", "Months_Searching",
    "Applications_Submitted", "First_Round_Interviews", "Second_Round_Interviews",
]
CATEGORICAL_COLS = [
    "University_Rating", "School_Size", "Region",
    "Major_Category", "Primary_Search_Platform",
]

# ── Reproduce preprocessing (identical to prepare.py) ─────────────────────────
print("[1/4] Loading and preprocessing data …")
df = pd.read_csv(DATA_PATH)
df = df.drop(columns=DROP_COLS, errors="ignore").drop_duplicates()

y = df[TARGET_COL].astype(int)
X = df.drop(columns=[TARGET_COL], errors="ignore")

X_cat_enc = pd.get_dummies(X[CATEGORICAL_COLS], drop_first=True)
X_full    = pd.concat([X[NUMERIC_COLS], X_cat_enc], axis=1)

X_train, _, y_train, _ = train_test_split(
    X_full, y, test_size=0.20, stratify=y, random_state=0
)

scaler = StandardScaler()
scaler.fit(X_train[NUMERIC_COLS])

# Column metadata
ohe_columns   = list(X_cat_enc.columns)       # e.g. ["University_Rating_Mid-tier", ...]
feature_names = list(X_train.columns)          # numeric cols then OHE cols

# Categorical dropdown values and which first value was dropped by drop_first
cat_values: dict = {}
cat_first_dropped: dict = {}
for col in CATEGORICAL_COLS:
    vals = sorted(df[col].dropna().unique().tolist())
    cat_values[col]        = vals
    cat_first_dropped[col] = str(vals[0])   # alphabetically first is dropped

print(f"   OHE columns ({len(ohe_columns)}): {ohe_columns}")
print(f"   Feature order ({len(feature_names)} total)")

# ── Load model ─────────────────────────────────────────────────────────────────
print("[2/4] Loading GBT model …")
model = joblib.load(MODEL_PATH)

# ── Convert to ONNX ────────────────────────────────────────────────────────────
print("[3/4] Converting GBT → ONNX …")
n_features = len(feature_names)
initial_type = [("float_input", FloatTensorType([None, n_features]))]
onnx_model = convert_sklearn(model, initial_types=initial_type,
                              options={"zipmap": False})   # output raw probabilities array

# ── Write output files ─────────────────────────────────────────────────────────
print("[4/4] Writing output files …")
OUT_LIB.mkdir(parents=True, exist_ok=True)
OUT_PUBLIC.mkdir(parents=True, exist_ok=True)

# model_offer.onnx — loaded by onnxruntime-web at runtime
onnx_path = OUT_PUBLIC / "model_offer.onnx"
with open(onnx_path, "wb") as f:
    f.write(onnx_model.SerializeToString())
size_kb = onnx_path.stat().st_size / 1024
print(f"   → public/model_offer.onnx  ({size_kb:.0f} KB)")

# preprocessing_offer.js — scaler params + OHE structure + form metadata
preproc = {
    "numericCols":     NUMERIC_COLS,
    "scalerMean":      scaler.mean_.tolist(),
    "scalerScale":     scaler.scale_.tolist(),
    "oheCols":         ohe_columns,
    "featureNames":    feature_names,
    "catCols":         CATEGORICAL_COLS,
    "catValues":       cat_values,
    "catFirstDropped": cat_first_dropped,
    "nFeatures":       n_features,
}
preproc_js = f"""\
// AUTO-GENERATED by export_to_js.py — do not edit manually.

export const PREPROCESSING = {json.dumps(preproc, indent=2)};
"""
(OUT_LIB / "preprocessing_offer.js").write_text(preproc_js, encoding="utf-8")
print("   → src/lib/preprocessing_offer.js")

print("\nDone!")
print(f"  ONNX model : {onnx_path.resolve()}")
print(f"  Preproc JS : {(OUT_LIB / 'preprocessing_offer.js').resolve()}")
