"""
train_and_compare.py
====================
Trains every model defined in a list of ModelSpec objects, runs two-round
staircase grid search for each one, and collects results into a ranked
comparison table with charts.

Architecture
------------
  train_and_export.py  →  prepare()  →  PreparedData
                       →  build_model_specs()  →  List[ModelSpec]
                       →  train_and_compare()  →  CompareResult

Two-round staircase grid search
--------------------------------
  Round 1  Coarse grid – wide, log-spaced or large-step ranges.
           Quickly locates the promising region of the hyperparameter space.
  Round 2  Fine grid   – generated by the per-spec refine_fn(best_params_1).
           Zooms in around the Round-1 optimum with smaller steps / tighter
           log-spacing to squeeze out the last fraction of performance.

Public API
----------
  specs   = build_model_specs()          # default specs; override in export
  result  = train_and_compare(data, specs, config)

  result.comparison_df                   # ranked DataFrame (test accuracy)
  result.train_results                   # List[TrainResult], one per model
  result.best_model_name                 # name of the highest-accuracy model
  result.summary()                       # print the ranked table

  # helpers exported for train_and_export.py
  zoom_int(center, step, n)              # fine int grid around a center value
  zoom_log(center, n, radius_decades)    # fine log grid around a center float

AI Usage
--------
This file was developed with the assistance of generative AI based on our previous work.
We ensured we understand and verify all AI-generated code, and we are responsible
for its correctness and suitability for our project.
"""

from __future__ import annotations

import time
import warnings
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from sklearn.calibration import CalibratedClassifierCV
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier
from sklearn.kernel_approximation import Nystroem
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier

from prepare import PreparedData

# ──────────────────────────────────────────────────────────────────────────────
# Fine-grid helper utilities
# ──────────────────────────────────────────────────────────────────────────────

def zoom_int(center: int, step: int, n: int) -> np.ndarray:
    """
    Symmetric integer grid around *center*.

    Example
    -------
    zoom_int(97, 2, 5)  →  [89, 91, 93, 95, 97, 99, 101, 103, 105]
                             (5 steps left and right, step size 2)
    """
    radius = step * n
    arr = np.arange(max(1, center - radius), center + radius + 1, step)
    return arr


def zoom_log(center: float, n: int = 5, radius_decades: float = 1.0) -> np.ndarray:
    """
    Log-spaced grid of *2*n+1* values centred (in log10) on *center*.

    Example
    -------
    zoom_log(0.05, n=3, radius_decades=0.5)
    → 7 points from 10^(log10(0.05)-0.5) to 10^(log10(0.05)+0.5)
    """
    log_c = np.log10(center)
    return np.logspace(log_c - radius_decades, log_c + radius_decades, num=2 * n + 1)


# ──────────────────────────────────────────────────────────────────────────────
# Data containers
# ──────────────────────────────────────────────────────────────────────────────

@dataclass
class ModelSpec:
    """
    Everything train_and_compare needs to train and tune one model.

    Attributes
    ----------
    name        : display name used in the comparison table
    estimator   : unfitted sklearn estimator (or Pipeline)
    dataset     : 'FE' (feature-engineered) | 'base' (pre-engineering)
    param_grid_1: coarse grid for Round 1
    refine_fn   : callable(best_params_1) → fine param_grid for Round 2
                  Return {} to skip Round 2 (e.g., Logistic Regression plain)
    cv          : cross-validation folds (default uses config value)
    scoring     : metric string (default uses config value)
    """
    name:         str
    estimator:    Any
    dataset:      str                            # 'FE' | 'base'
    param_grid_1: Dict[str, Any]
    refine_fn:    Callable[[Dict], Dict]
    cv:           Optional[int]  = None          # None → use global config
    scoring:      Optional[str]  = None          # None → use global config


@dataclass
class TrainResult:
    """Artefacts produced for one model after both grid-search rounds."""
    name:          str
    dataset:       str
    best_estimator: Any
    best_params_1: Dict
    best_params_2: Dict
    cv1_results:   pd.DataFrame
    cv2_results:   pd.DataFrame                  # empty if refine_fn returns {}
    val_accuracy_1: float
    val_accuracy_2: float                        # same as _1 if no Round 2
    test_accuracy: float
    y_pred:        np.ndarray
    class_report:  str
    train_seconds: float


@dataclass
class CompareResult:
    """
    Aggregated output of train_and_compare().

    Quick-access attributes
    -----------------------
    result.models                    # Dict[name → best_estimator]
    result.best_model                # the single best fitted estimator
    result.best_model_name           # its display name
    result["Random Forest (tuned)"]  # estimator by name (bracket syntax)
    """
    comparison_df:     pd.DataFrame      # ranked by test accuracy
    train_results:     List[TrainResult]
    baseline_accuracy: float
    models:            Dict[str, Any]    # name → fitted best_estimator

    # ── convenience accessors ────────────────────────────────────────────────

    @property
    def best_model_name(self) -> str:
        """Name of the model with the highest test accuracy."""
        return self.comparison_df.iloc[0]["Model"]

    @property
    def best_model(self) -> Any:
        """Fitted estimator with the highest test accuracy."""
        return self.models[self.best_model_name]

    def __getitem__(self, name: str) -> Any:
        """result['Model Name'] → fitted estimator."""
        if name not in self.models:
            available = list(self.models.keys())
            raise KeyError(
                f"No model named {name!r}.  Available: {available}"
            )
        return self.models[name]

    def summary(self) -> None:
        """Print the ranked comparison table."""
        print("\n" + "=" * 62)
        print(f"{'Rank':<5} {'Model':<35} {'Dataset':<7} {'TestAcc':>8}")
        print("=" * 62)
        for rank, row in self.comparison_df.iterrows():
            marker = " ◄" if row["Model"] == self.best_model_name else ""
            print(
                f"{rank:<5} {row['Model']:<35} {row['Dataset']:<7}"
                f" {row['Test Accuracy']:>8.4f}{marker}"
            )
        print("=" * 62)


# ──────────────────────────────────────────────────────────────────────────────
# Default ModelSpec definitions  (mirrors V4 notebook exactly)
# train_and_export.py may override or extend this list.
# ──────────────────────────────────────────────────────────────────────────────

def _no_round2(_: Dict) -> Dict:
    """Sentinel: skip Round 2."""
    return {}


def _refine_knn(best: Dict) -> Dict:
    """Zoom in around the best k with step=1, keep best weight & metric."""
    k     = int(best["n_neighbors"])
    return {
        "n_neighbors": zoom_int(k, step=1, n=3),
        "weights":     [best["weights"]],
        "metric":      [best["metric"]],
    }


def _refine_ridge(best: Dict) -> Dict:
    """Zoom in on log(C) ±0.5 decades."""
    return {"C": zoom_log(best["C"], n=5, radius_decades=0.5)}


def _refine_lasso(best: Dict) -> Dict:
    return {"C": zoom_log(best["C"], n=5, radius_decades=0.5)}


def _refine_svm(best: Dict) -> Dict:
    return {
        "estimator__C":    zoom_log(best["estimator__C"], n=5, radius_decades=0.5),
        "estimator__loss": [best["estimator__loss"]],
    }


def _refine_dt(best: Dict) -> Dict:
    d = best["max_depth"]
    return {
        "max_depth":         zoom_int(d, step=1, n=2) if d is not None
                             else [6, 8, 10, 12, None],
        "min_samples_split": [best["min_samples_split"]],
        "min_samples_leaf":  [best["min_samples_leaf"]],
    }


def _refine_rf(best: Dict) -> Dict:
    n = int(best["n_estimators"])
    d = int(best["max_depth"])
    return {
        "n_estimators": zoom_int(n, step=1, n=10),
        "max_depth":    zoom_int(d, step=1, n=2),
    }


def _refine_gbt(best: Dict) -> Dict:
    n  = int(best["n_estimators"])
    d  = int(best["max_depth"])
    lr = float(best["learning_rate"])
    return {
        "learning_rate": [lr],
        "n_estimators":  zoom_int(n, step=10, n=3),
        "max_depth":     zoom_int(d, step=1,  n=2),
    }


def _refine_kernel_svm(best: Dict) -> Dict:
    """
    Zoom in on gamma and C independently (±0.75 log-decades, 9 points each).
    n_components is held fixed at the Round-1 value — retuning it in Round 2
    would be too expensive because it controls the size of the feature map.

    Round-2 grid size: 9 × 9 × 1 = 81 combos (× cv folds).
    """
    return {
        "nystroem__gamma":        zoom_log(best["nystroem__gamma"],
                                           n=4, radius_decades=0.75),
        "clf__C":                 zoom_log(best["clf__C"],
                                           n=4, radius_decades=0.75),
        "nystroem__n_components": [best["nystroem__n_components"]],
    }


def build_model_specs() -> List[ModelSpec]:
    """
    Return the default list of ModelSpec objects matching the V4 notebook.

    train_and_export.py imports this and may add / remove / override specs
    before passing them to train_and_compare().
    """
    return [
        # ── KNN ───────────────────────────────────────────────────────────────
        ModelSpec(
            name      = "KNN (tuned)",
            estimator = KNeighborsClassifier(),
            dataset   = "FE",
            param_grid_1 = {
                "n_neighbors": np.arange(3, 32, 2),
                "weights":     ["uniform", "distance"],
                "metric":      ["euclidean", "manhattan"],
            },
            refine_fn = _refine_knn,
        ),

        # ── Logistic Regression (no regularization) ───────────────────────────
        ModelSpec(
            name      = "Logistic Regression",
            estimator = LogisticRegression(max_iter=1000, random_state=0),
            dataset   = "FE",
            param_grid_1 = {},                   # no hyperparams → fit once
            refine_fn = _no_round2,
        ),

        # ── Ridge Logistic Regression ─────────────────────────────────────────
        ModelSpec(
            name      = "Ridge Logistic Regression",
            estimator = LogisticRegression(
                penalty="l2", max_iter=3000, random_state=0
            ),
            dataset   = "FE",
            param_grid_1 = {
                "C": 1 / np.array([1e-4, 1e-2, 0.1, 1, 10, 100, 1e3, 1e4, 1e5])
            },
            refine_fn = _refine_ridge,
        ),

        # ── Lasso Logistic Regression ─────────────────────────────────────────
        ModelSpec(
            name      = "Lasso Logistic Regression",
            estimator = LogisticRegression(
                penalty="l1", solver="saga", max_iter=3000, random_state=0
            ),
            dataset   = "FE",
            param_grid_1 = {
                "C": 1 / np.array([1e-4, 1e-2, 0.1, 1, 10, 100, 1e3, 1e4, 1e5])
            },
            refine_fn = _refine_lasso,
        ),

        # ── LinearSVC (wrapped for predict_proba) ────────────────────────────
        ModelSpec(
            name      = "LinearSVC",
            estimator = CalibratedClassifierCV(
                LinearSVC(max_iter=5000, random_state=0)
            ),
            dataset   = "FE",
            param_grid_1 = {
                "estimator__C":    [1e-4, 1e-3, 1e-2, 0.1, 0.5, 1, 5, 10, 50, 100, 1000],
                "estimator__loss": ["hinge", "squared_hinge"],
            },
            refine_fn = _refine_svm,
        ),

        # ── Decision Tree ─────────────────────────────────────────────────────
        ModelSpec(
            name      = "Decision Tree (tuned)",
            estimator = DecisionTreeClassifier(random_state=0),
            dataset   = "base",
            param_grid_1 = {
                "max_depth":         [2, 3, 4, 5, 6, 8, 10, 15, None],
                "min_samples_split": [2, 10, 50],
                "min_samples_leaf":  [1, 5, 20],
            },
            refine_fn = _refine_dt,
        ),

        # ── Random Forest ─────────────────────────────────────────────────────
        ModelSpec(
            name      = "Random Forest (tuned)",
            estimator = RandomForestClassifier(random_state=0, n_jobs=1),
            dataset   = "base",
            param_grid_1 = {
                "n_estimators": np.arange(1, 501, 50),
                "max_depth":    np.arange(1, 26,  5),
            },
            refine_fn = _refine_rf,
        ),

        # ── Gradient Boosting ─────────────────────────────────────────────────
        ModelSpec(
            name      = "Gradient Boosting (tuned)",
            estimator = GradientBoostingClassifier(random_state=0),
            dataset   = "base",
            param_grid_1 = {
                "learning_rate": [0.01, 0.05, 0.1],
                "n_estimators":  [50, 100, 200, 300],
                "max_depth":     [1, 2, 3, 5, 7],
            },
            refine_fn = _refine_gbt,
        ),

        # ── Kernel SVM (Nystroem RBF approximation) ───────────────────────────
        # True RBF-SVC is O(n²–n³) and impractical for 80 k samples.
        # Nystroem maps the data into an n_components-dimensional feature space
        # that approximates the RBF kernel, then LogisticRegression draws a
        # linear boundary in that space — giving effectively kernel-SVM behaviour
        # at O(n × n_components) cost.  predict_proba is available natively.
        #
        # Round 1: gamma(8) × n_components(3) × C(8) = 192 combos
        #   gamma     : 1e-4 … 1e3  (8 log-spaced points, full RBF width range)
        #   n_components: 200/500/1000 (trades approximation quality vs. speed)
        #   C         : 1e-3 … 1e4  (8 log-spaced points)
        # Round 2: 9 × 9 × 1 = 81 combos; ±0.75 log-decades around R1 best
        ModelSpec(
            name      = "Kernel SVM (Nystroem RBF)",
            estimator = Pipeline([
                ("nystroem", Nystroem(kernel="rbf", random_state=0)),
                ("clf",      LogisticRegression(max_iter=2000, random_state=0)),
            ]),
            dataset   = "base",
            param_grid_1 = {
                "nystroem__gamma":        np.logspace(-4, 3, 8),   # 1e-4 … 1e3
                "nystroem__n_components": [200, 500, 1000],
                "clf__C":                 np.logspace(-3, 4, 8),   # 1e-3 … 1e4
            },
            refine_fn = _refine_kernel_svm,
        ),
    ]


# ──────────────────────────────────────────────────────────────────────────────
# Core training logic
# ──────────────────────────────────────────────────────────────────────────────

def _select_dataset(
    data: PreparedData, dataset: str
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """Return (X_train, X_test) for the requested dataset tag."""
    if dataset == "FE":
        return data.X_train_FE, data.X_test_FE
    if dataset == "base":
        return data.X_train_base, data.X_test_base
    raise ValueError(f"Unknown dataset tag '{dataset}'. Use 'FE' or 'base'.")


def _run_grid_search(
    estimator: Any,
    param_grid: Dict,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    cv: int,
    scoring: str,
) -> Tuple[Any, Dict, float, pd.DataFrame]:
    """
    Run a single GridSearchCV pass.

    Returns
    -------
    (best_estimator, best_params, best_score, cv_results_df)
    """
    gs = GridSearchCV(
        estimator,
        param_grid=param_grid,
        scoring=scoring,
        cv=cv,
        return_train_score=True,
        n_jobs=-1,
    )
    gs.fit(X_train, y_train)
    return (
        gs.best_estimator_,
        gs.best_params_,
        float(gs.best_score_),
        pd.DataFrame(gs.cv_results_),
    )


def _fit_direct(
    estimator: Any,
    X_train: pd.DataFrame,
    y_train: pd.Series,
    cv: int,
    scoring: str,
) -> Tuple[Any, Dict, float, pd.DataFrame]:
    """
    Fit the estimator once (no hyperparameters to search).
    Returns the same 4-tuple as _run_grid_search for uniform downstream handling.
    Estimates the 'best score' with a quick 3-fold CV for comparability.
    """
    from sklearn.model_selection import cross_val_score

    estimator.fit(X_train, y_train)
    cv_scores = cross_val_score(
        estimator, X_train, y_train,
        scoring=scoring, cv=min(cv, 3), n_jobs=-1
    )
    return (
        estimator,
        {},
        float(cv_scores.mean()),
        pd.DataFrame({"mean_test_score": cv_scores}),
    )


def _train_one(
    spec: ModelSpec,
    data: PreparedData,
    cv: int,
    scoring: str,
) -> TrainResult:
    """
    Train a single model through both grid-search rounds.

    Round 1  Coarse grid (or direct fit when param_grid_1 is empty).
    Round 2  Fine grid produced by spec.refine_fn(best_params_1).
             Skipped when refine_fn returns {}.
    """
    effective_cv      = spec.cv      if spec.cv      is not None else cv
    effective_scoring = spec.scoring if spec.scoring is not None else scoring

    X_train, X_test = _select_dataset(data, spec.dataset)
    y_train, y_test = data.y_train, data.y_test

    t0 = time.perf_counter()

    print(f"\n{'─'*62}")
    print(f"  Training : {spec.name}  [{spec.dataset}]")
    print(f"{'─'*62}")

    # ── Round 1 ──────────────────────────────────────────────────────────────
    if spec.param_grid_1:
        n_combos_1 = 1
        for v in spec.param_grid_1.values():
            n_combos_1 *= len(v)
        print(f"  Round 1 : coarse grid  ({n_combos_1} combos × {effective_cv}-fold CV)")

        best_est_1, best_p1, val_acc_1, cv1_df = _run_grid_search(
            spec.estimator, spec.param_grid_1,
            X_train, y_train, effective_cv, effective_scoring,
        )
        print(f"    best params : {best_p1}")
        print(f"    val accuracy: {val_acc_1:.4f}")
    else:
        print("  Round 1 : no hyperparameters — fitting directly.")
        best_est_1, best_p1, val_acc_1, cv1_df = _fit_direct(
            spec.estimator, X_train, y_train, effective_cv, effective_scoring
        )

    # ── Round 2 ──────────────────────────────────────────────────────────────
    fine_grid = spec.refine_fn(best_p1)

    if fine_grid:
        n_combos_2 = 1
        for v in fine_grid.values():
            n_combos_2 *= len(v)
        print(f"  Round 2 : fine grid    ({n_combos_2} combos × {effective_cv}-fold CV)")

        best_est_2, best_p2, val_acc_2, cv2_df = _run_grid_search(
            spec.estimator, fine_grid,
            X_train, y_train, effective_cv, effective_scoring,
        )
        print(f"    best params : {best_p2}")
        print(f"    val accuracy: {val_acc_2:.4f}")

        # Keep Round 2 result only if it is at least as good as Round 1
        if val_acc_2 >= val_acc_1:
            final_est = best_est_2
            final_p2  = best_p2
            final_v2  = val_acc_2
        else:
            warnings.warn(
                f"[{spec.name}] Round-2 val accuracy ({val_acc_2:.4f}) is lower "
                f"than Round 1 ({val_acc_1:.4f}). Keeping Round-1 estimator.",
                UserWarning,
                stacklevel=2,
            )
            final_est = best_est_1
            final_p2  = best_p1
            final_v2  = val_acc_1
    else:
        print("  Round 2 : skipped (refine_fn returned empty grid).")
        final_est = best_est_1
        final_p2  = {}
        final_v2  = val_acc_1
        cv2_df    = pd.DataFrame()

    # ── Test-set evaluation ───────────────────────────────────────────────────
    y_pred      = final_est.predict(X_test)
    test_acc    = float(accuracy_score(y_test, y_pred))
    cls_report  = classification_report(
        y_test, y_pred,
        target_names=[data.label_map[k] for k in sorted(data.label_map)],
    )

    elapsed = time.perf_counter() - t0
    print(f"  Test accuracy : {test_acc:.4f}   ({elapsed:.1f}s total)")

    return TrainResult(
        name           = spec.name,
        dataset        = spec.dataset,
        best_estimator = final_est,
        best_params_1  = best_p1,
        best_params_2  = final_p2,
        cv1_results    = cv1_df,
        cv2_results    = cv2_df,
        val_accuracy_1 = val_acc_1,
        val_accuracy_2 = final_v2,
        test_accuracy  = test_acc,
        y_pred         = y_pred,
        class_report   = cls_report,
        train_seconds  = elapsed,
    )


# ──────────────────────────────────────────────────────────────────────────────
# Individual prediction analysis
# ──────────────────────────────────────────────────────────────────────────────

def analyze_predictions(
    result: TrainResult,
    data: PreparedData,
    n_examples: int = 1,
) -> None:
    """
    For a given TrainResult, print the *n_examples* most-confident correct
    predictions (best) and *n_examples* most-confident wrong predictions (worst).

    Requires the estimator to support predict_proba.
    """
    X_test, _ = _select_dataset(data, result.dataset)
    y_test     = data.y_test.values
    y_pred     = result.y_pred

    try:
        proba = result.best_estimator.predict_proba(X_test)
    except AttributeError:
        print(f"  [{result.name}] predict_proba not available — skipping.")
        return

    # confidence = probability assigned to the TRUE class
    confidence = proba[np.arange(len(y_test)), y_test.astype(int)]

    correct_mask   = y_pred == y_test
    incorrect_mask = ~correct_mask

    label_map = data.label_map

    print(f"\n{'═'*62}")
    print(f"  Individual prediction analysis : {result.name}")
    print(f"{'═'*62}")

    for tag, mask, order in [
        ("BEST (correct, highest confidence)",   correct_mask,   "descending"),
        ("WORST (wrong,   highest confidence)",  incorrect_mask, "descending"),
    ]:
        idxs = np.where(mask)[0]
        if len(idxs) == 0:
            print(f"  {tag}: none found.")
            continue

        ranked = idxs[np.argsort(confidence[idxs])[::-1]][:n_examples]
        print(f"\n  ── {tag} ──")

        for i, idx in enumerate(ranked, 1):
            true_lbl  = label_map.get(int(y_test[idx]),  str(y_test[idx]))
            pred_lbl  = label_map.get(int(y_pred[idx]),  str(y_pred[idx]))
            conf      = confidence[idx]
            print(
                f"    #{i}  index={idx}"
                f"  true={true_lbl}"
                f"  predicted={pred_lbl}"
                f"  confidence={conf:.4f}"
            )
            # Show numeric feature values for this record
            num_vals = X_test.iloc[idx][data.numeric_cols]
            print("    numeric features:")
            for col, val in num_vals.items():
                print(f"      {col:<35s}: {val:+.3f}")


# ──────────────────────────────────────────────────────────────────────────────
# Feature importance (tree models)
# ──────────────────────────────────────────────────────────────────────────────

def _extract_feature_importance(
    train_results: List[TrainResult],
    feature_names: List[str],
    top_n: int = 10,
) -> Optional[pd.DataFrame]:
    """
    Build a comparison DataFrame of feature importances for tree-based models
    (Decision Tree, Random Forest, Gradient Boosting).

    Returns None if no tree model was trained.
    """
    tree_models = {
        r.name: r.best_estimator
        for r in train_results
        if hasattr(r.best_estimator, "feature_importances_")
    }

    if not tree_models:
        return None

    fi_df = pd.DataFrame({"Feature": feature_names})
    for name, est in tree_models.items():
        fi_df[name] = est.feature_importances_

    model_cols = list(tree_models.keys())
    primary    = model_cols[0]
    fi_df      = fi_df.sort_values(primary, ascending=False).head(top_n)

    return fi_df.reset_index(drop=True)


# ──────────────────────────────────────────────────────────────────────────────
# Main entry point
# ──────────────────────────────────────────────────────────────────────────────

def train_and_compare(
    data: PreparedData,
    specs: List[ModelSpec],
    config: Optional[Dict] = None,
) -> CompareResult:
    """
    Train every model in *specs*, evaluate on the test set, and return a
    CompareResult with the ranked comparison table and all per-model artefacts.

    Parameters
    ----------
    data   : PreparedData from prepare()
    specs  : list of ModelSpec (use build_model_specs() as a starting point)
    config : optional dict; recognised keys:
               cv          int   cross-validation folds       (default 5)
               scoring     str   sklearn scoring string       (default 'accuracy')
               n_examples  int   individual prediction count  (default 1)
               top_n_fi    int   feature importance top-N     (default 10)
               baseline_strategy  'most_frequent' | 'stratified'
    """
    if config is None:
        config = {}

    cv            : int = config.get("cv",            5)
    scoring       : str = config.get("scoring",       "accuracy")
    n_examples    : int = config.get("n_examples",    1)
    top_n_fi      : int = config.get("top_n_fi",      10)

    # ── Baseline ──────────────────────────────────────────────────────────────
    most_frequent = int(data.y_train.value_counts().idxmax())
    y_pred_base   = np.full(len(data.y_test), most_frequent)
    baseline_acc  = float(accuracy_score(data.y_test, y_pred_base))
    print(f"\n  Baseline (most-frequent class = {data.label_map.get(most_frequent, most_frequent)})"
          f"  test accuracy: {baseline_acc:.4f}")

    # ── Train each model ──────────────────────────────────────────────────────
    train_results: List[TrainResult] = []
    for spec in specs:
        result = _train_one(spec, data, cv, scoring)
        train_results.append(result)

    # ── Build ranked comparison table ─────────────────────────────────────────
    rows = [
        {
            "Model":         "Baseline (Most Frequent)",
            "Dataset":       "—",
            "Val Acc (R1)":  "—",
            "Val Acc (R2)":  "—",
            "Test Accuracy": baseline_acc,
            "Time (s)":      "—",
        }
    ]
    for r in train_results:
        rows.append({
            "Model":         r.name,
            "Dataset":       r.dataset,
            "Val Acc (R1)":  f"{r.val_accuracy_1:.4f}",
            "Val Acc (R2)":  f"{r.val_accuracy_2:.4f}",
            "Test Accuracy": r.test_accuracy,
            "Time (s)":      f"{r.train_seconds:.1f}",
        })

    comparison_df = (
        pd.DataFrame(rows)
        .sort_values("Test Accuracy", ascending=False)
        .reset_index(drop=True)
    )
    comparison_df.index = comparison_df.index + 1
    comparison_df.index.name = "Rank"

    # Pretty-format test accuracy only AFTER sorting
    comparison_df_display = comparison_df.copy()
    comparison_df_display["Test Accuracy"] = (
        comparison_df_display["Test Accuracy"].map("{:.4f}".format)
    )

    # ── Per-model classification reports ──────────────────────────────────────
    print("\n\n" + "═" * 62)
    print("  CLASSIFICATION REPORTS")
    print("═" * 62)
    for r in train_results:
        print(f"\n── {r.name} ──")
        print(r.class_report)

    # ── Individual prediction analysis ────────────────────────────────────────
    print("\n\n" + "═" * 62)
    print("  INDIVIDUAL PREDICTION ANALYSIS")
    print("═" * 62)
    for r in train_results:
        analyze_predictions(r, data, n_examples=n_examples)

    # ── Feature importance (tree models) ──────────────────────────────────────
    fi_df = _extract_feature_importance(
        train_results, data.feature_names, top_n=top_n_fi
    )
    if fi_df is not None:
        print("\n\n" + "═" * 62)
        print(f"  FEATURE IMPORTANCE — top {top_n_fi} (Base feature set)")
        print("═" * 62)
        print(fi_df.to_string(index=False))

    # ── Build models dict  (name → fitted estimator, ordered by rank) ────────
    ranked_names = list(comparison_df["Model"])          # best-first order
    models: Dict[str, Any] = {}
    for name in ranked_names:
        if name == "Baseline (Most Frequent)":
            continue
        match = next((r for r in train_results if r.name == name), None)
        if match:
            models[name] = match.best_estimator

    # ── Final summary ─────────────────────────────────────────────────────────
    result = CompareResult(
        comparison_df     = comparison_df,
        train_results     = train_results,
        baseline_accuracy = baseline_acc,
        models            = models,
    )
    result.summary()
    return result