// AUTO-GENERATED by export_to_js.py — do not edit manually.

export const PREPROCESSING = {
  "numericCols": [
    "GPA",
    "Prior_Internships",
    "Extra_Curricular_Activities",
    "Networking_Events_Attended",
    "Months_Searching",
    "Applications_Submitted",
    "First_Round_Interviews",
    "Second_Round_Interviews"
  ],
  "scalerMean": [
    3.197995125,
    1.1965875,
    2.0077125,
    3.002525,
    6.5093375,
    53.803825,
    2.1663875,
    1.0115125
  ],
  "scalerScale": [
    0.39254239799827273,
    1.122058757304514,
    1.4152130642923524,
    1.7351350449964984,
    3.4412334723313602,
    45.05246985870336,
    1.9069878604342898,
    1.138059735841555
  ],
  "oheCols": [
    "University_Rating_Mid-tier",
    "University_Rating_Top-tier",
    "School_Size_Medium",
    "School_Size_Small",
    "Region_Northeast",
    "Region_South",
    "Region_West",
    "Major_Category_Business",
    "Major_Category_Healthcare",
    "Major_Category_Humanities",
    "Major_Category_STEM",
    "Primary_Search_Platform_Indeed",
    "Primary_Search_Platform_LinkedIn"
  ],
  "featureNames": [
    "GPA",
    "Prior_Internships",
    "Extra_Curricular_Activities",
    "Networking_Events_Attended",
    "Months_Searching",
    "Applications_Submitted",
    "First_Round_Interviews",
    "Second_Round_Interviews",
    "University_Rating_Mid-tier",
    "University_Rating_Top-tier",
    "School_Size_Medium",
    "School_Size_Small",
    "Region_Northeast",
    "Region_South",
    "Region_West",
    "Major_Category_Business",
    "Major_Category_Healthcare",
    "Major_Category_Humanities",
    "Major_Category_STEM",
    "Primary_Search_Platform_Indeed",
    "Primary_Search_Platform_LinkedIn"
  ],
  "catCols": [
    "University_Rating",
    "School_Size",
    "Region",
    "Major_Category",
    "Primary_Search_Platform"
  ],
  "catValues": {
    "University_Rating": [
      "Lower-tier",
      "Mid-tier",
      "Top-tier"
    ],
    "School_Size": [
      "Large",
      "Medium",
      "Small"
    ],
    "Region": [
      "Midwest",
      "Northeast",
      "South",
      "West"
    ],
    "Major_Category": [
      "Arts",
      "Business",
      "Healthcare",
      "Humanities",
      "STEM"
    ],
    "Primary_Search_Platform": [
      "Handshake",
      "Indeed",
      "LinkedIn"
    ]
  },
  "catFirstDropped": {
    "University_Rating": "Lower-tier",
    "School_Size": "Large",
    "Region": "Midwest",
    "Major_Category": "Arts",
    "Primary_Search_Platform": "Handshake"
  },
  "nFeatures": 21
};
